name: Start AWS Resources

on:
  workflow_dispatch:

jobs:
  start-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-1

      - name: Start EC2 instances
        run: |
          echo "Starting all EC2 instances..."
          INSTANCE_IDS=$(aws ec2 describe-instances --region us-west-1 --query 'Reservations[*].Instances[*].InstanceId' --output text)
          if [ -n "$INSTANCE_IDS" ]; then
            aws ec2 start-instances --region us-west-1 --instance-ids $INSTANCE_IDS
          else
            echo "No EC2 instances found to start."
          fi

      - name: Start RDS instances
        run: |
          echo "Starting all RDS instances..."
          DB_INSTANCE_IDENTIFIERS=$(aws rds describe-db-instances --region us-west-1 --query 'DBInstances[*].DBInstanceIdentifier' --output text)
          if [ -n "$DB_INSTANCE_IDENTIFIERS" ]; then
            for DB_INSTANCE_IDENTIFIER in $DB_INSTANCE_IDENTIFIERS; do
              aws rds start-db-instance --region us-west-1 --db-instance-identifier $DB_INSTANCE_IDENTIFIER
            done
          else
            echo "No RDS instances found to start."
          fi
